
services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: ia-ds
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: iad_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d iad_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/initdb:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
